name: Terraform Checks

on:
  workflow_call:
    inputs:
      run-apply:
        description: 'Whether or not to run terraform apply'
        required: false
        default: false
        type: boolean
      terraform-version:
        description: 'Version of terraform to use'
        required: false
        default: '0.12.31'
        type: string
      iac-path:
        description: 'relative path to your IAC folder'
        required: false
        default: 'iac/develop'
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        description: 'AWS Access Key ID'
        required: true
      AWS_SECRET_ACCESS_KEY:
        description: 'AWS Secret Access Key'
        required: true
jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    environment: ${{ needs.determine-env.outputs.Environment }}
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Cache Comment Id
        id: cache-comment-id
        uses: actions/cache@v2.1.7
        with:
          path: comment-id
          key: pr-comment-id

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ inputs.terraform-version }}

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check

      - name: Terraform Init
        id: init
        run: |
          cd ${{ inputs.iac-path }}
          terraform init
      - name: Terraform Validate
        id: validate
        run: |
          cd ${{ inputs.iac-path }}
          terraform validate -no-color
      - name: Terraform Plan
        id: plan
        run: |
          cd ${{ inputs.iac-path }}
          terraform plan -no-color
        continue-on-error: true
